let AppMap =
    Application_AppNameIdMapping
    | where Timestamp between (_startTime .. _endTime)
    | where isnotempty(AppId)
    | summarize arg_max(Timestamp, AppName) by Host, AppId
    | project Host, AppId, AppName;
Process_ProcessDetail
| where Timestamp between (_startTime .. _endTime)
| where SessionID > 0
| join kind=leftouter AppMap on Host, AppId
| extend Application = iff(isnotempty(AppName), AppName, ProcName)
| where isnotempty(Application)
| summarize by Value = Application
| order by Value asc
