System_MachineInventory
| where Timestamp between (_startTime .. _endTime)
| extend HardwareModel = trim(" ", strcat(HwManufacturer, " ", HwModel))
| where Host in (_host) or isempty(_host)
| where OsName in (_osName) or isempty(_osName)
| where HardwareModel in (_hardwareModel) or isempty(_hardwareModel)
| where isnotnull(OsUpdateBuildRevision)
| extend OsBuildUbr = strcat(tostring(OsBuild), ".", tostring(OsUpdateBuildRevision))
| summarize HostCount = dcount(Host) by bin(Timestamp, 1d), OsBuildUbr
| order by Timestamp asc
