// Dashboard: Machine Health
// Version: 0.4.0
// Parameter: OS version
// Variable: _osVersion
// Query ID: 2620ed56-431d-4dc1-9db7-b3302ef2d7ea

System_MachineInventory
| where Timestamp between (
    _endTime - totimespan(_inventoryLookback) .. _endTime
)
| summarize arg_max(Timestamp, *) by Host
| where Host in (_host) or isempty(_host)
| where OsPlatform in (_osPlatform) or isempty(_osPlatform)
| where OsName in (_osName) or isempty(_osName)
| where isnotempty(OsVersion)
| summarize by Value = OsVersion
| order by Value asc