// Dashboard: Machine Health
// Version: 0.4.0
// Parameter: Hardware model
// Variable: _hardwareModel
// Query ID: 4ec3af0b-6b50-4fbf-aa5a-700418d58cac

System_MachineInventory
| where Timestamp between (
    _endTime - totimespan(_inventoryLookback) .. _endTime
)
| summarize arg_max(Timestamp, *) by Host
| where Host in (_host) or isempty(_host)
| where OsPlatform in (_osPlatform) or isempty(_osPlatform)
| where OsName in (_osName) or isempty(_osName)
| where OsVersion in (_osVersion) or isempty(_osVersion)
| extend Value = trim(
    " ",
    strcat(HwManufacturer, " ", HwModel)
)
| extend Value = iff(isempty(Value), "Unknown", Value)
| summarize by Value
| order by Value asc