System_SecurityInventory
| where Timestamp between (_startTime .. _endTime)
| where tostring(_inventoryCategory)=="" or tostring(_inventoryCategory)=="All" or tostring(SecurityInventoryCategory)==tostring(_inventoryCategory)
| where tostring(_inventoryName)=="" or tostring(_inventoryName)=="All" or tostring(SecurityInventoryName)==tostring(_inventoryName)| summarize arg_max(Timestamp, SecurityInventoryScope, SecurityInventoryRiskScore, SecurityInventoryScore, SecurityInventoryResultData) by SecurityInventoryName, SecurityInventoryCategory
| top 25 by SecurityInventoryRiskScore desc
| project SecurityInventoryName, SecurityInventoryCategory, SecurityInventoryScope, SecurityInventoryRiskScore, SecurityInventoryScore, Description=SecurityInventoryResultData, Timestamp
