ActivityMonitoring_ProcessTagging
| where Timestamp between (_startTime .. _endTime)
| where tostring(_host)=="" or tostring(_host)=="All" or Host==tostring(_host)
| where tostring(_process)=="" or tostring(_process)=="All" or ProcName==tostring(_process)
| where tostring(_ruleAnnotation)=="" or tostring(_ruleAnnotation)=="All" or tostring(RuleAnnotation)==tostring(_ruleAnnotation)| summarize AverageRisk=avg(ProcRiskScore1), MaxRisk=max(ProcRiskScore1) by bin(Timestamp,15m)
| order by Timestamp asc
