ActivityMonitoring_ProcessTagging
| where Timestamp between (_startTime .. _endTime)
| where tostring(_host)=="" or tostring(_host)=="All" or Host==tostring(_host)
| where tostring(_process)=="" or tostring(_process)=="All" or ProcName==tostring(_process)
| where tostring(_ruleAnnotation)=="" or tostring(_ruleAnnotation)=="All" or tostring(RuleAnnotation)==tostring(_ruleAnnotation)| extend RuleText=tostring(RuleAnnotation)
| where isnotempty(RuleText)
| summarize Value=count() by RuleText
| top 15 by Value desc
| project Category=RuleText, Value
