System_SecurityInventory
| where Timestamp between (_startTime .. _endTime)
| where tostring(_inventoryCategory)=="" or tostring(_inventoryCategory)=="All" or tostring(SecurityInventoryCategory)==tostring(_inventoryCategory)
| where tostring(_inventoryName)=="" or tostring(_inventoryName)=="All" or tostring(SecurityInventoryName)==tostring(_inventoryName)| where isnotempty(tostring(SecurityInventoryErrorCode))
| summarize Value=count() by SecurityInventoryCategory
| top 15 by Value desc
| project Category=tostring(SecurityInventoryCategory), Value
