System_SecurityInventory
| where Timestamp between (_startTime .. _endTime)
| where tostring(_inventoryCategory)=="" or tostring(_inventoryCategory)=="All" or tostring(SecurityInventoryCategory)==tostring(_inventoryCategory)
| where tostring(_inventoryName)=="" or tostring(_inventoryName)=="All" or tostring(SecurityInventoryName)==tostring(_inventoryName)| summarize arg_max(Timestamp, SecurityInventoryResultData, SecurityInventoryScope, SecurityInventoryRiskScore, SecurityInventoryScore, SecurityInventoryErrorCode, SecurityInventoryErrorMessage) by SecurityInventoryName, SecurityInventoryCategory
| project SecurityInventoryName, SecurityInventoryCategory, Description=SecurityInventoryResultData, Scope=SecurityInventoryScope, SecurityInventoryRiskScore, SecurityInventoryScore, SecurityInventoryErrorCode, SecurityInventoryErrorMessage, Timestamp
| order by SecurityInventoryCategory asc, SecurityInventoryName asc
