System_SecurityInventory
| where Timestamp between (_startTime .. _endTime)
| where tostring(_inventoryCategory)=="" or tostring(_inventoryCategory)=="All" or tostring(SecurityInventoryCategory)==tostring(_inventoryCategory)
| where isnotempty(SecurityInventoryName)
| summarize by SecurityInventoryName
| project Value=tostring(SecurityInventoryName), Label=tostring(SecurityInventoryName)
| union (print Value="All", Label="All")
| order by Label asc
