let TopN = tolong(_topN);
let AppMap =
    Application_AppNameIdMapping
    | where Timestamp between (_startTime .. _endTime)
    | where isnotempty(AppId)
    | summarize arg_max(Timestamp, AppName) by Host, AppId
    | project Host, AppId, AppName;
let ProcessBase =
    Process_ProcessDetail
    | where Timestamp between (_startTime .. _endTime)
    | where SessionID > 0
    | where Host in (_host) or isempty(_host)
    | where ProcUser in (_user) or isempty(_user)
    | where ProcName in (_process) or isempty(_process)
    | join kind=leftouter AppMap on Host, AppId
    | extend Application = iff(isnotempty(AppName), AppName, ProcName)
    | where isnotempty(Application)
    | where Application in (_application) or isempty(_application);
ProcessBase
| summarize
    Users = dcountif(ProcUser, isnotempty(ProcUser)),
    Hosts = dcount(Host),
    Sessions = dcount(strcat(Host, "|", tostring(SessionID))),
    ProcessInstances = dcount(ProcGUID),
    ProcessNames = dcount(ProcName),
    Versions = dcountif(AppVersion, isnotempty(AppVersion)),
    Samples = count(),
    FirstSeen = min(Timestamp),
    LastSeen = max(Timestamp)
    by Application
| top TopN by Users desc
