let StartTime=_startTime;
let EndTime=_endTime;
let UserFilter=tostring(_user);
let HostFilter=tostring(_host);
let SessionFilter=tostring(_session);
let ConfigurationCategoryFilter=tostring(_configurationCategory);
let ConfigLatest=materialize(CitrixSession_SessionConfig
| where Timestamp between (StartTime .. EndTime)
| extend User=tolower(SessionUser),SessionKey=tostring(SessionGUID)
| where isempty(UserFilter) or User =~ UserFilter
| where isempty(HostFilter) or Host =~ HostFilter
| where isempty(SessionFilter) or SessionKey == SessionFilter
| summarize arg_max(Timestamp,*) by SessionKey);
ConfigLatest
| project User,Host,SessionKey,SessionGUID,Timestamp,NetworkConnectedVia,NetworkEdtMtu,NetworkPolicyAcceptSessionReliabilityConnections,NetworkPolicySessionReliabilityPort,NetworkPolicySessionReliabilityTimeout,NetworkPolicyICAListenerPortNumber,DisplayMode,ThinwireVideoCodecType,ThinwireVideoCodecUse,ThinwireColorspace,ThinwireHardwareEncodeInUse,ThinwireColorDepth,ThinwireComponentEncoder,ThinwirePolicyFps,ThinwirePolicyPriority,ThinwirePolicyUseHardwareEncoding,ThinwirePolicyUseVideoCodec,ThinwirePolicyVisualQuality,AudioPolicyAllowRedirection,AudioPolicyAllowMicrophoneRedirection,AudioPolicySoundQuality,CdmPolicyAllowDriveRedirection,CdmPolicyReadOnly,CdmVolumes,PrinterPolicyAllowRedirection,PrinterPolicyAutoCreateClientPrinters,PrinterSessionPrinter,USBPolicyAllowUSBSupport,USBPolicyAllowPNPRedirection
| top 25 by Timestamp desc
