let VdaMachineRole = 0;
let RegisteredState = 1;
Citrix_Machines
| where Timestamp between (_startTime .. _endTime)
| where SiteName in (_site) or isempty(_site)
| where CatalogDisplayName in (_catalog) or isempty(_catalog)
| where DesktopGroupDisplayName in (_deliveryGroup) or isempty(_deliveryGroup)
| where NameHost in (_host) or isempty(_host)
| where isempty(_tag) or Tags contains _tag
| summarize arg_max(Timestamp, *) by Id
| where MachineRole == VdaMachineRole and CurrentRegistrationState != RegisteredState
| summarize UnregisteredVDAs = count() by ['Delivery group'] = DesktopGroupDisplayName
| where isnotempty(['Delivery group'])
| order by UnregisteredVDAs desc
