let VdaMachineRole = 0;
let RegisteredState = 1;
Citrix_Machines
| where Timestamp between (_startTime .. _endTime)
| where SiteName in (_site) or isempty(_site)
| where CatalogDisplayName in (_catalog) or isempty(_catalog)
| where DesktopGroupDisplayName in (_deliveryGroup) or isempty(_deliveryGroup)
| where NameHost in (_host) or isempty(_host)
| where isempty(_tag) or Tags contains _tag
| where MachineRole == VdaMachineRole
| where CurrentRegistrationState == RegisteredState
| summarize arg_max(Timestamp, CatalogDisplayName) by TimeBucket = bin(Timestamp, 1h), Id
| summarize RegisteredCount = dcount(Id) by TimeBucket, Catalog = CatalogDisplayName
| order by TimeBucket asc, Catalog asc
